- python/initialize.js
Update to convert checkElementBy to check_element, not to check_region
> Update checkElementBy to check_element

- coverage-tests.js
create for:
https://github.com/applitools/eyes.sdk.javascript1/pull/290
> chore: add test for correct layout region coordinates

- coverage-tests.js
with assertions and selectors types
> migrate mobileTest to the CT version 2+

- coverage-tests.js
- package.json
- python/initialize.js
- python/mapping/selectors.js
- python/parser.js
- python/python_requirements.txt
- python/test/conftest.py
> Add mobile native tests

- .gitignore
- coverage-tests.js
added .gitignore file
added missing `.ref("name")` to some tests.
> Fixes and improvements

- package.json
- python/initialize.js
- python/override-tests.js
- python/test/conftest.py
Add some mobile native tests to skip, add use of feature "Scale mobile app"
> Add some mobile native tests to skip

- coverage-tests.js
- js/overrides.js
Remove skipEmit for Appium tests
> Remove skipEmit for Appium tests

- python/initialize.js
Set SCALE_MOBILE_APP from enum
> Set SCALE_MOBILE_APP from enum

- README.md
I added instructions, examples, and overview for this project.
Let me know if you think anything should be added.
I left a few `TODO`s that we should fill.
> Update docs to new workflow

- DotNet/overrides.js
- coverage-tests.js
- java/overrides.js
- python/overrides.js
- ruby/overrides.js
[trello](https://trello.com/c/e2MbEs0r)  
adding test for custom batch properties
> chore: adding custom batch properties test

- DotNet/overrides.js
- coverage-tests.js
- java/overrides.js
- python/overrides.js
- ruby/overrides.js
Baselines:
* Chrome:
https://eyes.applitools.com/app/test-results/00000251790278873106/?accountId=xIpd7EWjhU6cjJzDGrMcUw~~
* Firefox:
https://eyes.applitools.com/app/test-results/00000251790278826763/?accountId=xIpd7EWjhU6cjJzDGrMcUw~~
> Add test for adoptedStyleSheets

- ruby/overrides.js
Remove skip for generic test 'should send ignore displacements with vg'
> Remove skip for generic test 'should send ignore displacements with vg'

- java/overrides.js
Remove skip for two generic tests java3. Tests have new baselines in new branch "current1"
> Remove skip for two generic tests java3

- python/overrides.js
Remove skip for 2 python generic tests
> Remove skip for 2 python generic tests

- DotNet/emitter.js
- DotNet/overrides.js
- DotNet/parser.js
Dot net add layout breakpoints
> Dot net add layout breakpoints

- java/overrides.js
Set special branch 'current_ruby' for java3 test 'check frame fully with css stitching'
Successful run - https://travis-ci.com/github/applitools/eyes.sdk.java3/builds/223393520
> Set special branch for java3 test 'check frame fully with css stitching'

- DotNet/overrides.js
- coverage-tests.js
- java/overrides.js
- java/parser.js
- js/overrides.js
- python/overrides.js
- ruby/overrides.js
Implementation of feature in JS:
https://github.com/applitools/eyes.sdk.javascript1/pull/416
> Add variant id tests

- python/emitter.js
- python/overrides.js
Add code for Python isDisabled config parameter
> Add code for Python isDisabled config parameter

- ruby/initialize.js
- ruby/overrides.js
- ruby/parser.js
> Ruby batch properties

- DotNet/overrides.js
- DotNet/parser.js
Add variationGroupId to Dotnet generator
> Add variationGroupId to Dotnet generator

- ruby/overrides.js
Set specific branch for Ruby test 'check region in frame hidden under top bar fully with scroll stitching'
> Set specific branch for Ruby test

- python/emitter.js
- python/overrides.js
Update python's emitter for Visual Locators tests
Successful run - https://travis-ci.com/github/applitools/eyes.sdk.python/builds/224986190
> Update python's emitter for Visual Locators tests

- python/emitter.js
- python/mapping/types.js
- python/overrides.js
Successful run - https://travis-ci.com/github/applitools/eyes.sdk.python/builds/226040202
> Updates for Python tests 'should send custom batch properties', 'adopted styleSheets on chrome'

- python/overrides.js
Successful run - https://travis-ci.com/github/applitools/eyes.sdk.python/builds/226079193
> Set special branch for 3 Python tests

- coverage-tests.js
> Update `should send ignore regions by selector` and `should send floating region by selector`
